/**
 * Tests for PDF/A compliance validation and enforcement.
 *
 * These tests exercise our internal PDF/A validation and enforcement
 * against PDFs generated by modern-pdf-lib's own createPdf() API,
 * verifying end-to-end compliance checking without requiring external
 * tools (veraPDF itself is only needed in CI via the script).
 *
 * Covers:
 * - validatePdfA detecting issues in standard (non-compliant) PDFs
 * - enforcePdfA injecting XMP metadata and file identifiers
 * - Enforcement reducing error counts vs. raw PDFs
 * - Encryption and JavaScript blocking in enforcement
 * - All supported conformance levels (1a/1b/2a/2b/2u/3a/3b/3u)
 * - Color space and output intent detection
 * - Standard font embedding warnings
 * - Document language detection
 * - Round-trip validation stability
 */

import { describe, it, expect } from 'vitest';
import { createPdf, PageSizes, rgb } from '../../src/index.js';
import { validatePdfA, enforcePdfA } from '../../src/compliance/index.js';
import type { PdfALevel } from '../../src/compliance/index.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const encoder = new TextEncoder();
const decoder = new TextDecoder();

/** Create a simple one-page PDF document and return its bytes. */
async function createSimplePdf(): Promise<Uint8Array> {
  const doc = createPdf();
  const page = doc.addPage(PageSizes.A4);
  page.drawText('Hello PDF/A', { x: 50, y: 750, size: 24, color: rgb(0, 0, 0) });
  return doc.save();
}

/** Build a minimal synthetic PDF for pattern-based tests. */
function buildSyntheticPdf(options: {
  metadata?: boolean;
  xmpPdfaId?: boolean;
  encrypt?: boolean;
  javascript?: boolean;
  trailerId?: boolean;
  lang?: boolean;
  deviceRgb?: boolean;
  outputIntents?: boolean;
  structTree?: boolean;
  markInfo?: boolean;
  toUnicode?: boolean;
  standardFont?: boolean;
} = {}): Uint8Array {
  const lines: string[] = ['%PDF-1.7'];

  let catalog = '<< /Type /Catalog /Pages 2 0 R';
  if (options.lang) catalog += ' /Lang (en)';
  if (options.structTree) catalog += ' /StructTreeRoot 10 0 R';
  if (options.markInfo) catalog += ' /MarkInfo << /Marked true >>';
  if (options.outputIntents) catalog += ' /OutputIntents [<< /Type /OutputIntent >>]';
  catalog += ' >>';

  lines.push('1 0 obj', catalog, 'endobj');
  lines.push('2 0 obj', '<< /Type /Pages /Kids [3 0 R] /Count 1 >>', 'endobj');

  let pageDict = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792]';
  if (options.deviceRgb) pageDict += ' /Resources << /ColorSpace << /CS1 /DeviceRGB >> >>';
  pageDict += ' >>';
  lines.push('3 0 obj', pageDict, 'endobj');

  if (options.metadata) {
    let xmp = '<x:xmpmeta xmlns:x="adobe:ns:meta/">';
    xmp += '<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">';
    if (options.xmpPdfaId) {
      xmp += '<rdf:Description xmlns:pdfaid="http://www.aiim.org/pdfa/ns/id/">';
      xmp += '<pdfaid:part>2</pdfaid:part>';
      xmp += '<pdfaid:conformance>B</pdfaid:conformance>';
      xmp += '</rdf:Description>';
    }
    xmp += '</rdf:RDF></x:xmpmeta>';
    lines.push('4 0 obj');
    lines.push(`<< /Type /Metadata /Subtype /XML /Length ${xmp.length} >>`);
    lines.push('stream');
    lines.push(xmp);
    lines.push('endstream');
    lines.push('endobj');
    lines[2] = lines[2]!.replace('/Pages 2 0 R', '/Pages 2 0 R /Metadata 4 0 R');
  }

  if (options.encrypt) {
    lines.push('5 0 obj', '<< /Filter /Standard /V 2 /R 3 /O (xxx) /U (xxx) /P -4 >>', 'endobj');
  }

  if (options.javascript) {
    lines.push('6 0 obj', '<< /Type /Action /S /JavaScript /JS (alert) >>', 'endobj');
  }

  if (options.toUnicode) {
    lines.push('7 0 obj', '<< /Type /Font /Subtype /TrueType /ToUnicode 8 0 R >>', 'endobj');
  }

  if (options.standardFont) {
    lines.push('12 0 obj', '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>', 'endobj');
  }

  lines.push('xref', '0 1', '0000000000 65535 f ');

  let trailer = '<< /Size 13 /Root 1 0 R';
  if (options.encrypt) trailer += ' /Encrypt 5 0 R';
  if (options.trailerId) trailer += ' /ID [<abc123> <def456>]';
  trailer += ' >>';
  lines.push('trailer', trailer, 'startxref', '0', '%%EOF');

  return encoder.encode(lines.join('\n'));
}

// ---------------------------------------------------------------------------
// Tests: validatePdfA with real PDFs from createPdf()
// ---------------------------------------------------------------------------

describe('PDF/A validation (internal)', () => {
  it('validatePdfA reports issues for a standard PDF', async () => {
    const bytes = await createSimplePdf();
    const result = validatePdfA(bytes, '1b');
    expect(result.level).toBe('1b');
    // A standard PDF won't have XMP metadata with PDF/A identification
    expect(result.issues.length).toBeGreaterThan(0);
  });

  it('enforcePdfA adds XMP metadata with pdfaid', async () => {
    const bytes = await createSimplePdf();
    const enforced = await enforcePdfA(bytes, '1b');
    expect(enforced.length).toBeGreaterThan(bytes.length);

    const text = decoder.decode(enforced);
    expect(text).toContain('pdfaid:part');
    expect(text).toContain('pdfaid:conformance');
  });

  it('enforcePdfA produces fewer errors than raw PDF', async () => {
    const bytes = await createSimplePdf();
    const beforeResult = validatePdfA(bytes, '1b');
    const enforced = await enforcePdfA(bytes, '1b');
    const afterResult = validatePdfA(enforced, '1b');

    const beforeErrors = beforeResult.issues.filter((i) => i.severity === 'error').length;
    const afterErrors = afterResult.issues.filter((i) => i.severity === 'error').length;

    expect(afterErrors).toBeLessThanOrEqual(beforeErrors);
  });

  it('validatePdfA does not report encryption for standard PDFs', async () => {
    const bytes = await createSimplePdf();
    const result = validatePdfA(bytes, '1b');
    const encryptIssue = result.issues.find((i) => i.code === 'PDFA-003');
    expect(encryptIssue).toBeUndefined();
  });

  it('validatePdfA does not report JavaScript for standard PDFs', async () => {
    const bytes = await createSimplePdf();
    const result = validatePdfA(bytes, '1b');
    const jsIssue = result.issues.find((i) => i.code === 'PDFA-004');
    expect(jsIssue).toBeUndefined();
  });

  it('validatePdfA flags missing XMP metadata', async () => {
    const bytes = await createSimplePdf();
    const result = validatePdfA(bytes, '1b');
    // Standard PDFs from createPdf() don't have /Metadata in the catalog
    const xmpIssue = result.issues.find(
      (i) => i.code === 'PDFA-001' || i.code === 'PDFA-002',
    );
    expect(xmpIssue).toBeDefined();
  });

  it('validates all supported levels without crashing', () => {
    const levels: PdfALevel[] = ['1b', '2b', '3b', '1a', '2a', '3a', '2u', '3u'];
    // Minimal valid PDF header bytes
    const pdfHeader = encoder.encode('%PDF-1.7\ntrailer\n<< /Size 0 /Root 1 0 R >>\nstartxref\n0\n%%EOF');
    for (const level of levels) {
      expect(() => validatePdfA(pdfHeader, level)).not.toThrow();
    }
  });

  it('enforcePdfA adds file ID to the trailer', async () => {
    const bytes = await createSimplePdf();
    const enforced = await enforcePdfA(bytes, '1b');
    const text = decoder.decode(enforced);
    expect(text).toContain('/ID');
  });

  it('enforcePdfA sets correct part number for each level', async () => {
    const bytes = await createSimplePdf();

    const enforced1 = await enforcePdfA(bytes, '1b');
    const text1 = decoder.decode(enforced1);
    expect(text1).toContain('<pdfaid:part>1</pdfaid:part>');
    expect(text1).toContain('<pdfaid:conformance>B</pdfaid:conformance>');

    const enforced2 = await enforcePdfA(bytes, '2b');
    const text2 = decoder.decode(enforced2);
    expect(text2).toContain('<pdfaid:part>2</pdfaid:part>');
    expect(text2).toContain('<pdfaid:conformance>B</pdfaid:conformance>');

    const enforced3 = await enforcePdfA(bytes, '3a');
    const text3 = decoder.decode(enforced3);
    expect(text3).toContain('<pdfaid:part>3</pdfaid:part>');
    expect(text3).toContain('<pdfaid:conformance>A</pdfaid:conformance>');
  });

  it('enforcePdfA returns the same bytes if already valid', async () => {
    // Build a synthetic PDF that passes all checks
    const pdf = buildSyntheticPdf({
      metadata: true,
      xmpPdfaId: true,
      trailerId: true,
      lang: true,
    });
    const preCheck = validatePdfA(pdf, '2b');
    if (preCheck.valid) {
      const enforced = await enforcePdfA(pdf, '2b');
      // Should be the same reference (no modifications needed)
      expect(enforced).toBe(pdf);
    }
  });

  it('enforcePdfA throws for encrypted PDFs', async () => {
    const pdf = buildSyntheticPdf({ encrypt: true });
    await expect(enforcePdfA(pdf, '2b')).rejects.toThrow('encrypted');
  });

  it('enforcePdfA throws for PDFs with JavaScript', async () => {
    const pdf = buildSyntheticPdf({ javascript: true });
    await expect(enforcePdfA(pdf, '2b')).rejects.toThrow('JavaScript');
  });

  it('validatePdfA detects missing language tag', async () => {
    const bytes = await createSimplePdf();
    const result = validatePdfA(bytes, '2b');
    const langIssue = result.issues.find((i) => i.code === 'PDFA-011');
    // Our simple PDF may or may not set /Lang, but the check shouldn't crash
    expect(typeof result.valid).toBe('boolean');
    // If /Lang is missing, there should be a warning
    if (langIssue) {
      expect(langIssue.severity).toBe('warning');
    }
  });

  it('validatePdfA detects unembedded standard fonts', () => {
    const pdf = buildSyntheticPdf({
      metadata: true,
      xmpPdfaId: true,
      trailerId: true,
      lang: true,
      standardFont: true,
    });
    const result = validatePdfA(pdf, '2b');
    const fontIssue = result.issues.find((i) => i.code === 'PDFA-013');
    expect(fontIssue).toBeDefined();
    expect(fontIssue!.message).toContain('Helvetica');
    expect(fontIssue!.severity).toBe('error');
  });

  it('validatePdfA warns about device color spaces without output intents', () => {
    const pdf = buildSyntheticPdf({
      metadata: true,
      xmpPdfaId: true,
      trailerId: true,
      lang: true,
      deviceRgb: true,
    });
    const result = validatePdfA(pdf, '2b');
    const colorIssue = result.issues.find((i) => i.code === 'PDFA-012');
    expect(colorIssue).toBeDefined();
    expect(colorIssue!.severity).toBe('warning');
  });

  it('validatePdfA does not warn about color when OutputIntents present', () => {
    const pdf = buildSyntheticPdf({
      metadata: true,
      xmpPdfaId: true,
      trailerId: true,
      lang: true,
      deviceRgb: true,
      outputIntents: true,
    });
    const result = validatePdfA(pdf, '2b');
    const colorIssue = result.issues.find((i) => i.code === 'PDFA-012');
    expect(colorIssue).toBeUndefined();
  });

  it('validatePdfA requires StructTreeRoot for "a" conformance', () => {
    const pdf = buildSyntheticPdf({
      metadata: true,
      xmpPdfaId: true,
      trailerId: true,
      lang: true,
    });
    const result = validatePdfA(pdf, '2a');
    const structIssue = result.issues.find((i) => i.code === 'PDFA-007');
    const markIssue = result.issues.find((i) => i.code === 'PDFA-008');
    expect(structIssue).toBeDefined();
    expect(markIssue).toBeDefined();
  });

  it('validatePdfA does not require StructTreeRoot for "b" conformance', () => {
    const pdf = buildSyntheticPdf({
      metadata: true,
      xmpPdfaId: true,
      trailerId: true,
      lang: true,
    });
    const result = validatePdfA(pdf, '2b');
    const structIssue = result.issues.find((i) => i.code === 'PDFA-007');
    expect(structIssue).toBeUndefined();
  });

  it('validatePdfA warns about missing ToUnicode for "u" conformance', () => {
    const pdf = buildSyntheticPdf({
      metadata: true,
      xmpPdfaId: true,
      trailerId: true,
      lang: true,
    });
    const result = validatePdfA(pdf, '2u');
    const unicodeIssue = result.issues.find((i) => i.code === 'PDFA-009');
    expect(unicodeIssue).toBeDefined();
    expect(unicodeIssue!.severity).toBe('warning');
  });

  it('enforcePdfA XMP metadata identifies the creator tool', async () => {
    const bytes = await createSimplePdf();
    const enforced = await enforcePdfA(bytes, '2b');
    const text = decoder.decode(enforced);
    expect(text).toContain('modern-pdf-lib');
  });

  it('enforcePdfA output passes more validation checks after enforcement', async () => {
    const bytes = await createSimplePdf();
    const before = validatePdfA(bytes, '2b');

    const enforced = await enforcePdfA(bytes, '2b');
    const after = validatePdfA(enforced, '2b');

    // XMP metadata should now be present
    const xmpMissingBefore = before.issues.some(
      (i) => i.code === 'PDFA-001' || i.code === 'PDFA-002',
    );
    const xmpMissingAfter = after.issues.some(
      (i) => i.code === 'PDFA-001',
    );

    // If XMP was missing before, it should not be missing after
    if (xmpMissingBefore) {
      expect(xmpMissingAfter).toBe(false);
    }
  });

  it('validation result includes the correct level field', () => {
    const pdf = buildSyntheticPdf();
    for (const level of ['1b', '2b', '3b', '1a', '2a', '3a', '2u', '3u'] as const) {
      const result = validatePdfA(pdf, level);
      expect(result.level).toBe(level);
    }
  });

  it('validation result issues have required fields', () => {
    const pdf = buildSyntheticPdf();
    const result = validatePdfA(pdf, '1b');
    for (const issue of result.issues) {
      expect(typeof issue.code).toBe('string');
      expect(issue.code.length).toBeGreaterThan(0);
      expect(typeof issue.message).toBe('string');
      expect(issue.message.length).toBeGreaterThan(0);
      expect(['error', 'warning']).toContain(issue.severity);
    }
  });

  it('enforcePdfA generates unique file IDs on each call', async () => {
    const bytes = await createSimplePdf();
    const enforced1 = await enforcePdfA(bytes, '1b');
    const enforced2 = await enforcePdfA(bytes, '1b');

    // Extract /ID values — they should differ between calls
    const text1 = decoder.decode(enforced1);
    const text2 = decoder.decode(enforced2);

    const idMatch1 = text1.match(/\/ID\s*\[<([a-f0-9]+)>/);
    const idMatch2 = text2.match(/\/ID\s*\[<([a-f0-9]+)>/);

    // Both should have IDs
    expect(idMatch1).not.toBeNull();
    expect(idMatch2).not.toBeNull();

    // IDs should be different (random)
    if (idMatch1 && idMatch2) {
      expect(idMatch1[1]).not.toBe(idMatch2[1]);
    }
  });
});
