/**
 * Tests for buildFormFromJsonSchema — generate a fillable AcroForm PDF
 * from a JSON-Schema-like description.
 *
 * These tests exercise the feature end-to-end: build the form, save the
 * PdfDocument to real PDF bytes, reload it with the parser, and assert
 * the round-tripped AcroForm contains the expected fields with the
 * expected types using the public form-reading API.
 */

import { describe, it, expect } from 'vitest';
import { PdfDocument } from '../../../src/core/pdfDocument.js';
import { PdfDict, PdfName, PdfRef } from '../../../src/core/pdfObjects.js';
import { PdfForm } from '../../../src/form/pdfForm.js';
import {
  buildFormFromJsonSchema,
  type JsonSchemaLike,
} from '../../../src/form/schemaForm.js';

/**
 * Read the AcroForm from a saved-then-loaded document via the public
 * {@link PdfForm.fromDict} API.
 *
 * NOTE: the library's parser does not currently rehydrate `/AcroForm`
 * into `doc.getForm()` on load (no `setForm()` call exists in the load
 * path), so `loaded.getForm()` would return an *empty* form regardless
 * of the PDF's contents. To verify the generated bytes actually contain
 * a real, parseable AcroForm, we locate the catalog in the loaded
 * registry, resolve its `/AcroForm`, and rebuild a `PdfForm` from it.
 */
function readAcroForm(loaded: PdfDocument): PdfForm {
  const registry = loaded.getRegistry();
  const resolver = (ref: PdfRef): PdfDict => {
    const obj = registry.resolve(ref);
    if (obj === undefined) throw new Error(`Unresolved ref ${ref.objectNumber}`);
    return obj as PdfDict;
  };

  let catalog: PdfDict | undefined;
  for (const { object } of registry) {
    if (object instanceof PdfDict) {
      const type = object.get('/Type');
      if (type instanceof PdfName && type.value === '/Catalog') {
        catalog = object;
        break;
      }
    }
  }
  if (catalog === undefined) throw new Error('No /Catalog in loaded registry');

  const afObj = catalog.get('/AcroForm');
  const acroFormDict = afObj instanceof PdfRef ? resolver(afObj) : (afObj as PdfDict);
  return PdfForm.fromDict(acroFormDict, (ref) => resolver(ref));
}

describe('buildFormFromJsonSchema', () => {
  // -------------------------------------------------------------------------
  // In-memory result shape (no save/load)
  // -------------------------------------------------------------------------

  it('emits one field per property mapping types correctly', () => {
    const schema: JsonSchemaLike = {
      type: 'object',
      properties: {
        fullName: { type: 'string' },
        subscribe: { type: 'boolean' },
        country: { type: 'string', enum: ['US', 'CA', 'MX'] },
      },
      required: ['fullName'],
    };

    const result = buildFormFromJsonSchema(schema);

    expect(result.fields).toHaveLength(3);

    const byName = new Map(result.fields.map((f) => [f.name, f.kind]));
    expect(byName.get('fullName')).toBe('text');
    expect(byName.get('subscribe')).toBe('checkbox');
    expect(byName.get('country')).toBe('dropdown');

    // Order is preserved (insertion order of properties).
    expect(result.fields.map((f) => f.name)).toEqual([
      'fullName',
      'subscribe',
      'country',
    ]);

    // The document is returned (not yet saved).
    expect(result.doc).toBeInstanceOf(PdfDocument);
    expect(result.doc.getPageCount()).toBeGreaterThanOrEqual(1);
  });

  it('maps number / integer to text fields', () => {
    const result = buildFormFromJsonSchema({
      type: 'object',
      properties: {
        age: { type: 'integer' },
        balance: { type: 'number' },
      },
    });
    const byName = new Map(result.fields.map((f) => [f.name, f.kind]));
    expect(byName.get('age')).toBe('text');
    expect(byName.get('balance')).toBe('text');
  });

  it('maps nested object / array to a text field placeholder', () => {
    const result = buildFormFromJsonSchema({
      type: 'object',
      properties: {
        address: { type: 'object', properties: { city: { type: 'string' } } },
        tags: { type: 'array' },
        unknownKeyword: { type: 'something-weird' },
        noType: {},
      },
    });
    const byName = new Map(result.fields.map((f) => [f.name, f.kind]));
    // Documented behaviour: unsupported / nested / unknown keywords all
    // degrade to a plain text field placeholder.
    expect(byName.get('address')).toBe('text');
    expect(byName.get('tags')).toBe('text');
    expect(byName.get('unknownKeyword')).toBe('text');
    expect(byName.get('noType')).toBe('text');
  });

  // -------------------------------------------------------------------------
  // End-to-end: save → load → read AcroForm
  // -------------------------------------------------------------------------

  it('produces a real PDF whose AcroForm round-trips with 3 typed fields', async () => {
    const schema: JsonSchemaLike = {
      type: 'object',
      title: 'Signup',
      properties: {
        fullName: { type: 'string', title: 'Full Name' },
        subscribe: { type: 'boolean' },
        country: { type: 'string', enum: ['US', 'CA', 'MX'] },
      },
      required: ['fullName'],
    };

    const { doc } = buildFormFromJsonSchema(schema);
    const bytes = await doc.save();

    // It must be a real, parseable PDF.
    expect(bytes.length).toBeGreaterThan(0);
    const header = new TextDecoder().decode(bytes.subarray(0, 5));
    expect(header).toBe('%PDF-');

    const loaded = await PdfDocument.load(bytes);
    const form = readAcroForm(loaded);
    const fields = form.getFields();

    expect(fields).toHaveLength(3);

    const byName = new Map(fields.map((f) => [f.getName(), f.fieldType]));
    expect(byName.get('fullName')).toBe('text');
    expect(byName.get('subscribe')).toBe('checkbox');
    expect(byName.get('country')).toBe('dropdown');

    // The dropdown's options survive the round-trip.
    const dropdown = form.getDropdown('country');
    expect(dropdown.getOptions()).toEqual(['US', 'CA', 'MX']);

    // The widgets must also be placed on a page (/Annots), not merely
    // listed in /AcroForm /Fields — otherwise viewers would not render
    // them. Assert the serialized bytes carry widget annotations.
    const raw = new TextDecoder('latin1').decode(bytes);
    expect(raw).toContain('/Annots');
    expect(raw).toContain('/Subtype /Widget');
  });

  it('paginates when many properties overflow the page', async () => {
    // Build a schema with enough properties to require multiple pages.
    const properties: Record<string, JsonSchemaLike> = {};
    for (let i = 0; i < 60; i++) {
      properties[`field_${i}`] = { type: 'string' };
    }

    const { doc, fields } = buildFormFromJsonSchema(
      { type: 'object', properties },
      { pageSize: [595.28, 841.89] },
    );

    expect(fields).toHaveLength(60);
    // The stacked fields must overflow a single A4 page.
    expect(doc.getPageCount()).toBeGreaterThan(1);

    // All 60 fields survive the save → load round-trip.
    const bytes = await doc.save();
    const loaded = await PdfDocument.load(bytes);
    expect(readAcroForm(loaded).getFields()).toHaveLength(60);
  });

  it('marks required fields in their drawn label (asterisk)', () => {
    // Required marking is a visual concern; we assert it does not throw
    // and that the required field is still emitted with the right kind.
    const result = buildFormFromJsonSchema({
      type: 'object',
      properties: { email: { type: 'string' } },
      required: ['email'],
    });
    expect(result.fields).toEqual([{ name: 'email', kind: 'text' }]);
  });

  it('returns an empty field list for a non-object / property-less schema', () => {
    const result = buildFormFromJsonSchema({ type: 'string' });
    expect(result.fields).toHaveLength(0);
    expect(result.doc).toBeInstanceOf(PdfDocument);
  });
});
