import { defineConfig, type DefaultTheme } from 'vitepress';

/**
 * The guide sidebar.
 *
 * Shared by the site root (`/`) and `/guide/` so that Getting Started and the
 * Playground are navigable too — a page whose path matches no sidebar key
 * renders with no sidebar at all.
 *
 * Every file in `docs/guide/` appears here exactly once. When you add a guide,
 * add it to the group it belongs to.
 */
const guideSidebar: DefaultTheme.SidebarItem[] = [
  {
    text: 'Introduction',
    items: [
      { text: 'Getting Started', link: '/getting-started' },
      { text: 'Coordinates', link: '/guide/coordinates' },
      { text: 'Cookbook', link: '/guide/cookbook' },
      { text: 'Troubleshooting', link: '/guide/troubleshooting' },
      { text: 'Playground', link: '/playground/' },
    ],
  },
  {
    text: 'Drawing Content',
    collapsed: false,
    items: [
      { text: 'Text', link: '/guide/text' },
      { text: 'Text Layout', link: '/guide/text-layout' },
      { text: 'Fonts', link: '/guide/fonts' },
      { text: 'Images', link: '/guide/images' },
      { text: 'Shapes', link: '/guide/shapes' },
      { text: 'Table Layout', link: '/guide/tables' },
      { text: 'Headers & Footers', link: '/guide/headers-footers' },
    ],
  },
  {
    text: 'Images & Color',
    collapsed: true,
    items: [
      { text: 'Image Formats', link: '/guide/image-formats' },
      { text: 'Image Optimization', link: '/guide/image-optimization' },
      { text: 'JPEG 2000 Support', link: '/guide/jpeg2000' },
      { text: 'Spot Colors & DeviceN', link: '/guide/spot-colors' },
    ],
  },
  {
    text: 'Interactive Documents',
    collapsed: true,
    items: [
      { text: 'Annotations', link: '/guide/annotations' },
      { text: 'Form Scripting', link: '/guide/form-scripts' },
      { text: 'Barcodes & QR Codes', link: '/guide/barcodes' },
    ],
  },
  {
    text: 'Signing & Trust',
    collapsed: true,
    items: [
      { text: 'Digital Signatures', link: '/guide/signatures' },
      { text: 'Signature Verification', link: '/guide/verification' },
      { text: 'Multi-Party Signing', link: '/guide/multi-sign' },
      { text: 'Security & Redaction', link: '/guide/security' },
    ],
  },
  {
    text: 'Standards & Compliance',
    collapsed: true,
    items: [
      { text: 'PDF/A Compliance', link: '/guide/pdfa' },
      { text: 'PDF/X Compliance', link: '/guide/pdfx' },
      { text: 'PDF 2.0 Core', link: '/guide/pdf2' },
      { text: 'Accessibility', link: '/guide/accessibility' },
    ],
  },
  {
    text: 'Output & Scale',
    collapsed: true,
    items: [
      { text: 'Streaming', link: '/guide/streaming' },
      { text: 'Streaming Parser', link: '/guide/streaming-parser' },
      { text: 'Performance', link: '/guide/performance' },
      { text: 'Batch Processing', link: '/guide/batch-processing' },
      { text: 'Rendering & Rasterization', link: '/guide/rendering' },
    ],
  },
  {
    text: 'Platform & Integration',
    collapsed: true,
    items: [
      { text: 'Browser Integration', link: '/guide/browser' },
      { text: 'Content Security Policy', link: '/guide/csp' },
      { text: 'Framework Integration', link: '/guide/framework-integration' },
      { text: 'Builder Pattern', link: '/guide/builder' },
      { text: 'Plugins', link: '/guide/plugins' },
    ],
  },
];

export default defineConfig({
  title: 'Modern PDF',
  description:
    'A modern, WASM-accelerated PDF creation engine for every JavaScript runtime',
  base: '/modern-pdf-lib/',

  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: '/logo.svg' }],
    ['meta', { name: 'theme-color', content: '#7C3AED' }],
    [
      'meta',
      {
        property: 'og:title',
        content: 'Modern PDF — WASM-Accelerated PDF Creation',
      },
    ],
    [
      'meta',
      {
        property: 'og:description',
        content:
          'A modern, WASM-accelerated PDF creation engine for every JavaScript runtime',
      },
    ],
    ['meta', { property: 'og:type', content: 'website' }],
    [
      'meta',
      {
        property: 'og:url',
        content: 'https://abcrimson.github.io/modern-pdf-lib/',
      },
    ],
    ['meta', { name: 'twitter:card', content: 'summary_large_image' }],
    [
      'link',
      { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
    ],
    [
      'link',
      {
        rel: 'preconnect',
        href: 'https://fonts.gstatic.com',
        crossorigin: '',
      },
    ],
  ],

  lastUpdated: true,
  cleanUrls: true,
  ignoreDeadLinks: [
    // Links *into* the generated API reference.
    /\/api\//,
    // Links *inside* the generated API reference. `docs/api/` is TypeDoc
    // output, regenerated by `npm run docs:api` on every docs deploy. When two
    // exported symbols differ only in case (`asPDFName` / `asPdfName`), TypeDoc
    // disambiguates the filename on a case-insensitive filesystem
    // (`asPDFName-1.md`) but still emits the original link target — so its
    // cross-references can dangle when the snapshot is generated on Windows.
    // Generated output must never fail the site build; every hand-written page
    // is still dead-link checked.
    (_link: string, source: string) =>
      source.replaceAll('\\', '/').includes('/docs/api/'),
  ],

  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'Modern PDF',

    nav: [
      { text: 'Guide', link: '/getting-started' },
      { text: 'API', link: '/api/' },
      { text: 'Migration', link: '/migration/from-pdf-lib' },
      { text: 'Playground', link: '/playground/' },
      {
        text: 'v0.40.2',
        items: [
          {
            text: 'Changelog',
            link: 'https://github.com/ABCrimson/modern-pdf-lib/blob/master/CHANGELOG.md',
          },
          {
            text: 'npm',
            link: 'https://www.npmjs.com/package/modern-pdf-lib',
          },
        ],
      },
    ],

    sidebar: {
      '/guide/': guideSidebar,
      '/getting-started': guideSidebar,
      '/playground/': guideSidebar,
      '/api/': [
        {
          text: 'API Reference',
          items: [{ text: 'Overview', link: '/api/' }],
        },
        {
          text: 'Core Classes',
          collapsed: false,
          items: [
            { text: 'PdfDocument', link: '/api/classes/PdfDocument' },
            { text: 'PdfPage', link: '/api/classes/PdfPage' },
            { text: 'PdfForm', link: '/api/classes/PdfForm' },
            { text: 'PdfStream', link: '/api/classes/PdfStream' },
          ],
        },
        {
          text: 'Form Fields',
          collapsed: true,
          items: [
            { text: 'PdfField', link: '/api/classes/PdfField' },
            { text: 'PdfTextField', link: '/api/classes/PdfTextField' },
            { text: 'PdfCheckboxField', link: '/api/classes/PdfCheckboxField' },
            { text: 'PdfDropdownField', link: '/api/classes/PdfDropdownField' },
            { text: 'PdfRadioGroup', link: '/api/classes/PdfRadioGroup' },
            { text: 'PdfListboxField', link: '/api/classes/PdfListboxField' },
            { text: 'PdfButtonField', link: '/api/classes/PdfButtonField' },
            { text: 'PdfSignatureField', link: '/api/classes/PdfSignatureField' },
          ],
        },
        {
          text: 'Annotations',
          collapsed: true,
          items: [
            { text: 'PdfAnnotation', link: '/api/classes/PdfAnnotation' },
            { text: 'PdfTextAnnotation', link: '/api/classes/PdfTextAnnotation' },
            { text: 'PdfLinkAnnotation', link: '/api/classes/PdfLinkAnnotation' },
            { text: 'PdfHighlightAnnotation', link: '/api/classes/PdfHighlightAnnotation' },
            { text: 'PdfFreeTextAnnotation', link: '/api/classes/PdfFreeTextAnnotation' },
            { text: 'PdfStampAnnotation', link: '/api/classes/PdfStampAnnotation' },
            { text: 'PdfRedactAnnotation', link: '/api/classes/PdfRedactAnnotation' },
          ],
        },
        {
          text: 'Key Interfaces',
          collapsed: true,
          items: [
            { text: 'DrawTextOptions', link: '/api/interfaces/DrawTextOptions' },
            { text: 'DrawImageOptions', link: '/api/interfaces/DrawImageOptions' },
            { text: 'DrawTableOptions', link: '/api/interfaces/DrawTableOptions' },
            { text: 'FontRef', link: '/api/interfaces/FontRef' },
            { text: 'ImageRef', link: '/api/interfaces/ImageRef' },
            { text: 'PdfSaveOptions', link: '/api/interfaces/PdfSaveOptions' },
            { text: 'LoadPdfOptions', link: '/api/interfaces/LoadPdfOptions' },
            { text: 'InitWasmOptions', link: '/api/interfaces/InitWasmOptions' },
          ],
        },
      ],
      '/migration/': [
        {
          text: 'Migration',
          items: [
            { text: 'From pdf-lib', link: '/migration/from-pdf-lib' },
          ],
        },
      ],
    },

    socialLinks: [
      {
        icon: 'github',
        link: 'https://github.com/ABCrimson/modern-pdf-lib',
      },
      { icon: 'npm', link: 'https://www.npmjs.com/package/modern-pdf-lib' },
    ],

    search: {
      provider: 'local',
    },

    editLink: {
      pattern:
        'https://github.com/ABCrimson/modern-pdf-lib/edit/master/docs/:path',
      text: 'Edit this page on GitHub',
    },

    footer: {
      message: 'Released under the MIT License.',
      copyright: 'Copyright 2026-present Modern PDF Contributors',
    },
  },
});
