/**
 * @module assets/font/textShaper
 *
 * Complex text layout (shaping) using rustybuzz WASM.
 *
 * For scripts that require ligature substitution, mark positioning, or
 * other OpenType layout features (Arabic, Devanagari, Thai, etc.), a
 * simple cmap lookup is insufficient.  This module delegates to
 * rustybuzz — a pure-Rust port of HarfBuzz compiled to WebAssembly —
 * for full OpenType shaping.
 *
 * When the WASM module is unavailable the module falls back to a naive
 * "simple shaper" that performs a plain cmap lookup (one codepoint →
 * one glyph).  This is adequate for Latin, Greek, Cyrillic, and most
 * CJK text but will produce incorrect results for complex scripts.
 *
 * No Node APIs — uses Uint8Array exclusively.
 */

import type { FontMetrics } from './fontMetrics.js';
import { getGlyphId, getGlyphWidth } from './fontMetrics.js';

// ---------------------------------------------------------------------------
// Public interfaces
// ---------------------------------------------------------------------------

/**
 * Position information for a single shaped glyph.
 */
export interface ShapedGlyph {
  /** Glyph ID in the font. */
  readonly glyphId: number;
  /** The Unicode codepoint(s) that produced this glyph. */
  readonly cluster: number;
  /** Horizontal advance in font design units. */
  readonly xAdvance: number;
  /** Vertical advance in font design units (usually 0 for horizontal text). */
  readonly yAdvance: number;
  /** Horizontal offset from the current pen position (kerning, mark positioning). */
  readonly xOffset: number;
  /** Vertical offset from the current pen position (mark positioning). */
  readonly yOffset: number;
}

/**
 * The result of shaping a text string.
 */
export interface ShapingResult {
  /** Ordered list of shaped glyphs (in visual order). */
  readonly glyphs: readonly ShapedGlyph[];
  /** Total advance width in font design units. */
  readonly totalAdvance: number;
}

/**
 * Direction for text layout.
 */
export type TextDirection = 'ltr' | 'rtl';

/**
 * OpenType script tag (ISO 15924).
 * Common examples: 'latn', 'arab', 'deva', 'cyrl', 'grek', 'hang'
 */
export type ScriptTag = string;

/**
 * OpenType language system tag.
 * Common examples: 'ENG ', 'ARA ', 'DEV ', 'dflt'
 */
export type LanguageTag = string;

/**
 * Options for text shaping.
 */
export interface ShapingOptions {
  /** Text direction.  Default: `'ltr'`. */
  readonly direction?: TextDirection;
  /** OpenType script tag.  Default: auto-detect or `'latn'`. */
  readonly script?: ScriptTag;
  /** OpenType language tag.  Default: `'dflt'`. */
  readonly language?: LanguageTag;
  /**
   * Explicit list of OpenType feature tags to enable/disable.
   * Each entry is `[tag, enabled]` — e.g. `[['liga', true], ['kern', true]]`.
   * When omitted, default shaping features for the script are applied.
   */
  readonly features?: readonly (readonly [string, boolean])[];
}

// ---------------------------------------------------------------------------
// WASM module state
// ---------------------------------------------------------------------------

/**
 * Holds the rustybuzz WASM module after initialization.
 * `undefined` means WASM has not been loaded (fallback mode).
 */
let wasmModule: RustybuzzWasmModule | undefined;

/**
 * Interface for the wasm-bindgen ShapingResult object.
 *
 * Getters return flat `Uint8Array` buffers in little-endian format:
 * - `glyph_ids`: 2 bytes per glyph (LE u16)
 * - `x_advances`, `y_advances`, `x_offsets`, `y_offsets`: 4 bytes per value (LE i32)
 * - `clusters`: 4 bytes per value (LE u32)
 *
 * @internal
 */
interface ShapingResultWasm {
  /** Number of output glyphs. */
  readonly glyph_count: number;
  /** Glyph IDs as flat LE u16 bytes. */
  readonly glyph_ids: Uint8Array;
  /** Horizontal advances as flat LE i32 bytes. */
  readonly x_advances: Uint8Array;
  /** Vertical advances as flat LE i32 bytes. */
  readonly y_advances: Uint8Array;
  /** Horizontal offsets as flat LE i32 bytes. */
  readonly x_offsets: Uint8Array;
  /** Vertical offsets as flat LE i32 bytes. */
  readonly y_offsets: Uint8Array;
  /** Cluster indices as flat LE u32 bytes. */
  readonly clusters: Uint8Array;
  /** Free the WASM-allocated result. */
  free(): void;
}

/**
 * Interface for the rustybuzz wasm-bindgen module exports.
 *
 * This matches the JS glue code generated by `wasm-pack build` for
 * `src/wasm/shaping/`. The functions accept high-level types (Uint8Array,
 * string) — wasm-bindgen handles all marshalling automatically.
 *
 * @internal
 */
interface RustybuzzWasmModule {
  /**
   * Shape text with auto-detected script/language.
   *
   * @param font_data  Complete font file bytes.
   * @param text       Unicode text string.
   * @param direction  0=LTR, 1=RTL, 2=TTB, 3=BTT.
   */
  shape_text(font_data: Uint8Array, text: string, direction: number): ShapingResultWasm;
  /**
   * Shape text with explicit script and language tags.
   *
   * @param font_data  Complete font file bytes.
   * @param text       Unicode text string.
   * @param direction  0=LTR, 1=RTL, 2=TTB, 3=BTT.
   * @param script     OpenType script tag (e.g. "latn", "arab"). Empty = auto.
   * @param language   OpenType language tag (e.g. "ENG "). Empty = default.
   */
  shape_text_with_features(
    font_data: Uint8Array,
    text: string,
    direction: number,
    script: string,
    language: string,
  ): ShapingResultWasm;
}

// ---------------------------------------------------------------------------
// WASM initialization
// ---------------------------------------------------------------------------

/**
 * Initialize the rustybuzz WASM module for complex text shaping.
 *
 * Call this once at application startup if you need to render complex
 * scripts (Arabic, Devanagari, etc.).  If not called, the library
 * falls back to simple cmap-based shaping.
 *
 * @param wasmSource - The `.wasm` binary as a Uint8Array, URL, or
 *                     Response.  When omitted the function attempts to
 *                     locate the binary relative to the package.
 * @returns A promise that resolves when the module is ready.
 */
export async function initShapingWasm(
  wasmSource?: RustybuzzWasmModule | Uint8Array | URL | string | Response,
): Promise<void> {
  // Already initialized -- no-op
  if (wasmModule) return;

  try {
    // If the caller passed a pre-built wasm-bindgen module, use it directly
    if (wasmSource && typeof (wasmSource as RustybuzzWasmModule).shape_text === 'function') {
      wasmModule = wasmSource as RustybuzzWasmModule;
      return;
    }

    // Otherwise, try to import the wasm-bindgen JS glue module.
    // The wasm-bindgen build produces a JS module that handles all
    // memory management and type marshalling automatically.
    // Raw WebAssembly.instantiate does NOT work with wasm-bindgen
    // because the WASM binary requires wasm-bindgen host imports
    // (__wbindgen_string_new, __wbindgen_throw, etc.).
    const { loadWasmModule: loadWasm } = await import('../../wasm/loader.js');
    const wasmBytes = await loadWasm('shaping');

    // Attempt to instantiate — this requires the wasm-bindgen JS glue.
    // If only raw WASM bytes are available (no glue), this will fail
    // and we fall back to the JS shaper.
    const imports = { env: {} };
    const result = await WebAssembly.instantiate(
      wasmBytes.buffer as ArrayBuffer,
      imports,
    );
    wasmModule = result.instance.exports as unknown as RustybuzzWasmModule;
  } catch {
    // WASM unavailable — fall back to simple cmap-based shaping.
    // This is expected when the WASM module hasn't been compiled
    // (no pkg/ directory) or the runtime doesn't support WASM.
    wasmModule = undefined;
  }
}

/**
 * Check whether the WASM shaper has been initialized.
 *
 * @returns `true` if {@link initShapingWasm} completed successfully.
 */
export function isShapingWasmReady(): boolean {
  return wasmModule !== undefined;
}

// ---------------------------------------------------------------------------
// WASM-accelerated shaping
// ---------------------------------------------------------------------------

/**
 * Shape text using the rustybuzz WASM module.
 *
 * Calls the wasm-bindgen exported `shape_text_with_features()`,
 * parses the flat little-endian byte arrays from the `ShapingResultWasm`
 * into `ShapedGlyph` objects, and frees the WASM result.
 *
 * @internal Only called when `wasmModule` is defined.
 */
function shapeWithWasm(
  fontData: Uint8Array,
  text: string,
  options: ShapingOptions,
): ShapingResult {
  const direction = options.direction === 'rtl' ? 1 : 0;
  const script = options.script ?? '';
  const language = options.language ?? '';

  const result = wasmModule!.shape_text_with_features(
    fontData,
    text,
    direction,
    script,
    language,
  );

  const count = result.glyph_count;
  const glyphIdBytes = result.glyph_ids;
  const xAdvBytes = result.x_advances;
  const yAdvBytes = result.y_advances;
  const xOffBytes = result.x_offsets;
  const yOffBytes = result.y_offsets;
  const clusterBytes = result.clusters;

  const glyphs: ShapedGlyph[] = [];
  let totalAdvance = 0;

  // Parse parallel LE byte arrays into ShapedGlyph objects
  const glyphIdView = new DataView(glyphIdBytes.buffer, glyphIdBytes.byteOffset, glyphIdBytes.byteLength);
  const xAdvView = new DataView(xAdvBytes.buffer, xAdvBytes.byteOffset, xAdvBytes.byteLength);
  const yAdvView = new DataView(yAdvBytes.buffer, yAdvBytes.byteOffset, yAdvBytes.byteLength);
  const xOffView = new DataView(xOffBytes.buffer, xOffBytes.byteOffset, xOffBytes.byteLength);
  const yOffView = new DataView(yOffBytes.buffer, yOffBytes.byteOffset, yOffBytes.byteLength);
  const clusterView = new DataView(clusterBytes.buffer, clusterBytes.byteOffset, clusterBytes.byteLength);

  for (let i = 0; i < count; i++) {
    const glyphId = glyphIdView.getUint16(i * 2, true); // LE u16
    const xAdvance = xAdvView.getInt32(i * 4, true);     // LE i32
    const yAdvance = yAdvView.getInt32(i * 4, true);     // LE i32
    const xOffset = xOffView.getInt32(i * 4, true);      // LE i32
    const yOffset = yOffView.getInt32(i * 4, true);      // LE i32
    const cluster = clusterView.getUint32(i * 4, true);  // LE u32

    glyphs.push({ glyphId, cluster, xAdvance, yAdvance, xOffset, yOffset });
    totalAdvance += xAdvance;
  }

  // Free the WASM-allocated result
  result.free();

  return { glyphs, totalAdvance };
}

// ---------------------------------------------------------------------------
// Simple fallback shaper (cmap-based)
// ---------------------------------------------------------------------------

/**
 * Simple shaper that maps each codepoint to a glyph via the cmap table.
 *
 * This is sufficient for most Latin, Greek, Cyrillic, and CJK text
 * but does **not** handle:
 * - Ligature substitution (fi, ffl, etc.)
 * - Mark positioning (combining diacritics)
 * - Arabic joining
 * - Indic conjuncts
 * - Kerning (GPOS)
 *
 * @internal
 */
function shapeSimple(
  text: string,
  metrics: FontMetrics,
  options: ShapingOptions,
): ShapingResult {
  const direction = options.direction ?? 'ltr';
  const glyphs: ShapedGlyph[] = [];
  let totalAdvance = 0;

  // Iterate codepoints (handles surrogate pairs correctly)
  const codepoints: { cp: number; idx: number }[] = [];
  let idx = 0;
  for (const char of text) {
    const cp = char.codePointAt(0)!;
    codepoints.push({ cp, idx });
    idx += char.length;
  }

  // For RTL, reverse the visual order
  if (direction === 'rtl') {
    codepoints.reverse();
  }

  for (const { cp, idx: cluster } of codepoints) {
    const glyphId = getGlyphId(cp, metrics.cmapTable);
    const xAdvance = getGlyphWidth(glyphId, metrics.glyphWidths, metrics.defaultWidth);

    glyphs.push({
      glyphId,
      cluster,
      xAdvance,
      yAdvance: 0,
      xOffset: 0,
      yOffset: 0,
    });

    totalAdvance += xAdvance;
  }

  return { glyphs, totalAdvance };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Shape a text string for rendering with the given font.
 *
 * If the rustybuzz WASM module has been initialized via
 * {@link initShapingWasm}, this performs full OpenType shaping
 * (ligatures, kerning, mark positioning, etc.).
 *
 * Otherwise it falls back to a simple cmap lookup — adequate for
 * Latin/Greek/Cyrillic/CJK but incorrect for Arabic, Devanagari,
 * Thai, and other complex scripts.
 *
 * @param text     - The Unicode text string to shape.
 * @param fontData - The raw TTF/OTF font file bytes.
 * @param metrics  - Pre-extracted font metrics (from `extractMetrics()`).
 * @param options  - Shaping options (direction, script, language, features).
 * @returns A promise resolving to the shaped glyph sequence.
 */
export async function shapeText(
  text: string,
  fontData: Uint8Array,
  metrics: FontMetrics,
  options: ShapingOptions = {},
): Promise<ShapingResult> {
  if (text.length === 0) {
    return { glyphs: [], totalAdvance: 0 };
  }

  if (wasmModule) {
    return shapeWithWasm(fontData, text, options);
  }

  return shapeSimple(text, metrics, options);
}

/**
 * Synchronous shaping using only the simple fallback shaper.
 *
 * Use this when you know you are only dealing with simple scripts and
 * want to avoid the async overhead.
 *
 * @param text    - The Unicode text string to shape.
 * @param metrics - Pre-extracted font metrics.
 * @param options - Shaping options.
 * @returns The shaped glyph sequence.
 */
export function shapeTextSync(
  text: string,
  metrics: FontMetrics,
  options: ShapingOptions = {},
): ShapingResult {
  if (text.length === 0) {
    return { glyphs: [], totalAdvance: 0 };
  }

  return shapeSimple(text, metrics, options);
}

/**
 * Convert shaped glyphs into a set of glyph IDs (useful for subsetting).
 *
 * @param result - A shaping result from {@link shapeText} or {@link shapeTextSync}.
 * @returns A Set of unique glyph IDs used by the shaped text.
 */
export function glyphIdsFromShapingResult(result: ShapingResult): Set<number> {
  const ids = new Set<number>();
  for (const glyph of result.glyphs) {
    ids.add(glyph.glyphId);
  }
  return ids;
}

/**
 * Compute the total advance width of a ShapingResult at a given font
 * size in points.
 *
 * @param result      - The shaping result.
 * @param fontSize    - The font size in points.
 * @param unitsPerEm  - The font's units-per-em value.
 * @returns The width in points.
 */
export function shapingResultWidth(
  result: ShapingResult,
  fontSize: number,
  unitsPerEm: number,
): number {
  return (result.totalAdvance / unitsPerEm) * fontSize;
}
