/**
 * @module scripts/generate-inline-wasm
 *
 * Build-time code generation script that reads each WASM module's compiled
 * binary from `src/wasm/<name>/pkg/*.wasm`, base64-encodes it, and writes
 * a generated TypeScript file at `src/wasm/inlineWasm.generated.ts`.
 *
 * The generated file exports a constant map of module names to their
 * base64-encoded WASM bytes. At runtime, the inline WASM loader decodes
 * these constants on demand, avoiding any filesystem or network access.
 *
 * Usage:
 *   npx tsx scripts/generate-inline-wasm.ts
 *
 * This is registered as `npm run generate:wasm-inline` in package.json.
 */

import { readFile, writeFile, access } from 'node:fs/promises';
import { resolve, join } from 'node:path';

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/** All known WASM module names and their expected binary filenames. */
const WASM_MODULES: ReadonlyArray<{ name: string; filename: string }> = [
  { name: 'libdeflate', filename: 'modern_pdf_libdeflate_bg.wasm' },
  { name: 'png',        filename: 'modern_pdf_png_bg.wasm' },
  { name: 'ttf',        filename: 'modern_pdf_ttf_bg.wasm' },
  { name: 'shaping',    filename: 'modern_pdf_shaping_bg.wasm' },
  { name: 'jbig2',      filename: 'modern_pdf_jbig2_bg.wasm' },
  { name: 'jpeg',       filename: 'modern_pdf_jpeg_bg.wasm' },
];

const ROOT_DIR = resolve(import.meta.dirname!, '..');
const WASM_SRC_DIR = join(ROOT_DIR, 'src', 'wasm');
const OUTPUT_FILE = join(WASM_SRC_DIR, 'inlineWasm.generated.ts');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const entries: Array<{ name: string; base64: string; sizeBytes: number }> = [];
  const skipped: string[] = [];

  for (const mod of WASM_MODULES) {
    const wasmPath = join(WASM_SRC_DIR, mod.name, 'pkg', mod.filename);

    if (!(await fileExists(wasmPath))) {
      skipped.push(mod.name);
      continue;
    }

    const wasmBytes = await readFile(wasmPath);
    const uint8 = new Uint8Array(wasmBytes.buffer, wasmBytes.byteOffset, wasmBytes.byteLength);
    const base64 = uint8.toBase64();

    entries.push({
      name: mod.name,
      base64,
      sizeBytes: wasmBytes.byteLength,
    });
  }

  // -----------------------------------------------------------------------
  // Generate TypeScript source
  // -----------------------------------------------------------------------

  const lines: string[] = [
    '/**',
    ' * @module wasm/inlineWasm.generated',
    ' *',
    ' * AUTO-GENERATED FILE -- DO NOT EDIT MANUALLY.',
    ' *',
    ' * Generated by `scripts/generate-inline-wasm.ts`.',
    ` * Generated at: ${new Date().toISOString()}`,
    ' *',
    ' * Contains base64-encoded WASM module binaries for inline embedding.',
    ' * Each constant is decoded at runtime by `getInlineWasmBytes()` in',
    ' * `src/wasm/inlineWasm.ts`.',
    ' */',
    '',
    '// ---------------------------------------------------------------------------',
    '// Inline WASM module data',
    '// ---------------------------------------------------------------------------',
    '',
  ];

  for (const entry of entries) {
    lines.push(`/**`);
    lines.push(` * Base64-encoded WASM binary for the \`${entry.name}\` module.`);
    lines.push(` * Original size: ${entry.sizeBytes.toLocaleString()} bytes.`);
    lines.push(` */`);
    lines.push(`export const WASM_${entry.name.toUpperCase()}_BASE64 = '${entry.base64}';`);
    lines.push('');
  }

  // Export a lookup map
  lines.push('// ---------------------------------------------------------------------------');
  lines.push('// Module name → base64 lookup');
  lines.push('// ---------------------------------------------------------------------------');
  lines.push('');
  lines.push('/** Map of WASM module names to their base64-encoded binaries. */');
  lines.push('export const INLINE_WASM_MODULES: Readonly<Record<string, string>> = {');
  for (const entry of entries) {
    lines.push(`  ${entry.name}: WASM_${entry.name.toUpperCase()}_BASE64,`);
  }
  lines.push('};');
  lines.push('');

  // Export the set of available module names
  lines.push('/** Names of all WASM modules that have inline binaries available. */');
  lines.push(`export const INLINE_WASM_MODULE_NAMES: readonly string[] = [${entries.map(e => `'${e.name}'`).join(', ')}];`);
  lines.push('');

  await writeFile(OUTPUT_FILE, lines.join('\n'), 'utf-8');

  // -----------------------------------------------------------------------
  // Report
  // -----------------------------------------------------------------------

  console.log('generate-inline-wasm: code generation complete.');
  console.log(`  Output: ${OUTPUT_FILE}`);
  console.log(`  Modules embedded: ${entries.length}`);
  for (const entry of entries) {
    const kbSize = (entry.sizeBytes / 1024).toFixed(1);
    const b64Kb = (entry.base64.length / 1024).toFixed(1);
    console.log(`    - ${entry.name}: ${kbSize} KB binary -> ${b64Kb} KB base64`);
  }
  if (skipped.length > 0) {
    console.log(`  Skipped (not compiled): ${skipped.join(', ')}`);
  }
}

main().catch((err: unknown) => {
  console.error('generate-inline-wasm: fatal error:', err);
  process.exitCode = 1;
});
