/**
 * @module scripts/generate-inline-wasm
 *
 * Build-time code generation script that reads each WASM module's compiled
 * binary from `src/wasm/<name>/pkg/*.wasm`, base64-encodes it, and writes
 * a generated TypeScript file at `src/wasm/inlineWasm.generated.ts`.
 *
 * The generated file exports:
 * - Individual per-module constants (tree-shakeable by bundlers)
 * - A lookup map for runtime access
 * - Size metadata for diagnostics
 *
 * At runtime, the inline WASM loader decodes these constants on demand,
 * avoiding any filesystem or network access.
 *
 * Usage:
 *   npx tsx scripts/generate-inline-wasm.ts
 *
 * This is registered as `npm run generate:wasm-inline` in package.json.
 */

import { readFile, writeFile, access } from 'node:fs/promises';
import { resolve, join } from 'node:path';

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

/** All known WASM module names and their expected binary filenames. */
const WASM_MODULES: ReadonlyArray<{ name: string; filename: string }> = [
  { name: 'libdeflate', filename: 'modern_pdf_libdeflate_bg.wasm' },
  { name: 'png',        filename: 'modern_pdf_png_bg.wasm' },
  { name: 'ttf',        filename: 'modern_pdf_ttf_bg.wasm' },
  { name: 'shaping',    filename: 'modern_pdf_shaping_bg.wasm' },
  { name: 'jbig2',      filename: 'modern_pdf_jbig2_bg.wasm' },
  { name: 'jpeg',       filename: 'modern_pdf_jpeg_bg.wasm' },
];

const ROOT_DIR = resolve(import.meta.dirname!, '..');
const WASM_SRC_DIR = join(ROOT_DIR, 'src', 'wasm');
const OUTPUT_FILE = join(WASM_SRC_DIR, 'inlineWasm.generated.ts');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Format a byte count as a human-readable string with appropriate unit.
 */
function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

// ---------------------------------------------------------------------------
// Size report type
// ---------------------------------------------------------------------------

interface ModuleSizeEntry {
  name: string;
  binarySize: number;
  base64Size: number;
  overhead: number;       // base64Size - binarySize
  overheadPercent: number; // (overhead / binarySize) * 100
}

interface SizeReport {
  generatedAt: string;
  modules: ModuleSizeEntry[];
  totalBinarySize: number;
  totalBase64Size: number;
  totalOverhead: number;
  totalOverheadPercent: number;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const entries: Array<{ name: string; base64: string; sizeBytes: number }> = [];
  const skipped: string[] = [];

  for (const mod of WASM_MODULES) {
    const wasmPath = join(WASM_SRC_DIR, mod.name, 'pkg', mod.filename);

    if (!(await fileExists(wasmPath))) {
      skipped.push(mod.name);
      continue;
    }

    const wasmBytes = await readFile(wasmPath);
    const uint8 = new Uint8Array(wasmBytes.buffer, wasmBytes.byteOffset, wasmBytes.byteLength);
    const base64 = uint8.toBase64();

    entries.push({
      name: mod.name,
      base64,
      sizeBytes: wasmBytes.byteLength,
    });
  }

  // -----------------------------------------------------------------------
  // Build size report
  // -----------------------------------------------------------------------

  const sizeReport: SizeReport = buildSizeReport(entries);

  // -----------------------------------------------------------------------
  // Generate TypeScript source
  // -----------------------------------------------------------------------

  const lines: string[] = [
    '/**',
    ' * @module wasm/inlineWasm.generated',
    ' *',
    ' * AUTO-GENERATED FILE -- DO NOT EDIT MANUALLY.',
    ' *',
    ' * Generated by `scripts/generate-inline-wasm.ts`.',
    ` * Generated at: ${new Date().toISOString()}`,
    ' *',
    ' * Contains base64-encoded WASM module binaries for inline embedding.',
    ' * Each module is exported as a separate constant for tree-shaking:',
    ' * bundlers can exclude unused modules from the final bundle.',
    ' *',
    ' * Size report:',
    ` *   Total binary: ${formatBytes(sizeReport.totalBinarySize)}`,
    ` *   Total base64: ${formatBytes(sizeReport.totalBase64Size)}`,
    ` *   Overhead: ${formatBytes(sizeReport.totalOverhead)} (+${sizeReport.totalOverheadPercent.toFixed(1)}%)`,
    ' *',
    ...sizeReport.modules.map(m =>
      ` *   - ${m.name}: ${formatBytes(m.binarySize)} binary -> ${formatBytes(m.base64Size)} base64 (+${m.overheadPercent.toFixed(1)}%)`
    ),
    ' */',
    '',
    '// ---------------------------------------------------------------------------',
    '// Per-module exports (tree-shakeable)',
    '// ---------------------------------------------------------------------------',
    '//',
    '// Each module is exported as a separate named constant. Bundlers that',
    '// support tree-shaking (Rollup, esbuild, webpack 5+) will exclude',
    '// unused modules from the final bundle. Import only what you need:',
    '//',
    '//   import { WASM_LIBDEFLATE_BASE64 } from "./inlineWasm.generated.js";',
    '//',
    '// If you import the INLINE_WASM_MODULES map, all modules will be included.',
    '',
  ];

  for (const entry of entries) {
    lines.push(`/**`);
    lines.push(` * Base64-encoded WASM binary for the \`${entry.name}\` module.`);
    lines.push(` * Original size: ${entry.sizeBytes.toLocaleString()} bytes.`);
    lines.push(` *`);
    lines.push(` * @remarks Tree-shakeable — only included in the bundle if imported.`);
    lines.push(` */`);
    lines.push(`/* @__PURE__ */ export const WASM_${entry.name.toUpperCase()}_BASE64 = '${entry.base64}';`);
    lines.push('');
  }

  // Export a lookup map
  lines.push('// ---------------------------------------------------------------------------');
  lines.push('// Module name -> base64 lookup');
  lines.push('// ---------------------------------------------------------------------------');
  lines.push('');
  lines.push('/**');
  lines.push(' * Map of WASM module names to their base64-encoded binaries.');
  lines.push(' *');
  lines.push(' * Importing this map prevents tree-shaking of individual modules.');
  lines.push(' * Prefer importing per-module constants directly if you only need');
  lines.push(' * a subset of modules.');
  lines.push(' */');
  lines.push('export const INLINE_WASM_MODULES: Readonly<Record<string, string>> = {');
  for (const entry of entries) {
    lines.push(`  ${entry.name}: WASM_${entry.name.toUpperCase()}_BASE64,`);
  }
  lines.push('};');
  lines.push('');

  // Export the set of available module names
  lines.push('/** Names of all WASM modules that have inline binaries available. */');
  lines.push(`export const INLINE_WASM_MODULE_NAMES: readonly string[] = [${entries.map(e => `'${e.name}'`).join(', ')}];`);
  lines.push('');

  // Export size metadata
  lines.push('// ---------------------------------------------------------------------------');
  lines.push('// Size metadata (for diagnostics / bundle analysis)');
  lines.push('// ---------------------------------------------------------------------------');
  lines.push('');
  lines.push('/**');
  lines.push(' * Size information for each inline WASM module.');
  lines.push(' *');
  lines.push(' * - `binarySize`: original .wasm file size in bytes');
  lines.push(' * - `base64Size`: base64-encoded string length in characters');
  lines.push(' */');
  lines.push('export const INLINE_WASM_SIZES: Readonly<Record<string, { binarySize: number; base64Size: number }>> = {');
  for (const entry of entries) {
    const b64Len = entry.base64.length;
    lines.push(`  ${entry.name}: { binarySize: ${entry.sizeBytes}, base64Size: ${b64Len} },`);
  }
  lines.push('};');
  lines.push('');

  await writeFile(OUTPUT_FILE, lines.join('\n'), 'utf-8');

  // -----------------------------------------------------------------------
  // Console report
  // -----------------------------------------------------------------------

  console.log('generate-inline-wasm: code generation complete.');
  console.log(`  Output: ${OUTPUT_FILE}`);
  console.log(`  Modules embedded: ${entries.length}`);
  console.log('');
  console.log('  Size report:');
  console.log(`    ${'Module'.padEnd(12)} ${'Binary'.padStart(10)} ${'Base64'.padStart(10)} ${'Overhead'.padStart(10)}`);
  console.log(`    ${''.padEnd(12, '-')} ${''.padEnd(10, '-')} ${''.padEnd(10, '-')} ${''.padEnd(10, '-')}`);

  for (const m of sizeReport.modules) {
    console.log(
      `    ${m.name.padEnd(12)} ${formatBytes(m.binarySize).padStart(10)} ${formatBytes(m.base64Size).padStart(10)} ${(`+${m.overheadPercent.toFixed(1)}%`).padStart(10)}`
    );
  }

  console.log(`    ${''.padEnd(12, '-')} ${''.padEnd(10, '-')} ${''.padEnd(10, '-')} ${''.padEnd(10, '-')}`);
  console.log(
    `    ${'TOTAL'.padEnd(12)} ${formatBytes(sizeReport.totalBinarySize).padStart(10)} ${formatBytes(sizeReport.totalBase64Size).padStart(10)} ${(`+${sizeReport.totalOverheadPercent.toFixed(1)}%`).padStart(10)}`
  );
  console.log('');

  if (skipped.length > 0) {
    console.log(`  Skipped (not compiled): ${skipped.join(', ')}`);
  }
}

// ---------------------------------------------------------------------------
// Size report builder
// ---------------------------------------------------------------------------

function buildSizeReport(
  entries: ReadonlyArray<{ name: string; base64: string; sizeBytes: number }>,
): SizeReport {
  const modules: ModuleSizeEntry[] = entries.map(entry => {
    const base64Size = entry.base64.length;
    const overhead = base64Size - entry.sizeBytes;
    return {
      name: entry.name,
      binarySize: entry.sizeBytes,
      base64Size,
      overhead,
      overheadPercent: entry.sizeBytes > 0 ? (overhead / entry.sizeBytes) * 100 : 0,
    };
  });

  const totalBinarySize = modules.reduce((sum, m) => sum + m.binarySize, 0);
  const totalBase64Size = modules.reduce((sum, m) => sum + m.base64Size, 0);
  const totalOverhead = totalBase64Size - totalBinarySize;

  return {
    generatedAt: new Date().toISOString(),
    modules,
    totalBinarySize,
    totalBase64Size,
    totalOverhead,
    totalOverheadPercent: totalBinarySize > 0 ? (totalOverhead / totalBinarySize) * 100 : 0,
  };
}

main().catch((err: unknown) => {
  console.error('generate-inline-wasm: fatal error:', err);
  process.exitCode = 1;
});
