/**
 * @module accessibility/taggingHelpers
 *
 * Ergonomic, high-level helpers for building a tagged-PDF logical
 * structure tree.  Each helper is a thin, type-safe wrapper around
 * {@link PdfStructureTree.addElement} that fixes the structure type and
 * fills in the conventional child structure for common constructs:
 *
 * - **Headings** — {@link tagHeading} (`H1`..`H6`).
 * - **Paragraphs** — {@link tagParagraph} (`P`).
 * - **Figures** — {@link tagFigure} (`Figure`, with required alt text).
 * - **Links** — {@link tagLink} (`Link`).
 * - **Lists** — {@link tagList} (`L`) and {@link tagListItem}
 *   (`LI` → `Lbl` + `LBody`).
 * - **Tables** — {@link tagTable} (`Table`), {@link tagTableRow} (`TR`),
 *   {@link tagTableHeaderCell} (`TH`, with a header scope) and
 *   {@link tagTableDataCell} (`TD`).
 *
 * These helpers do not introduce any new state: they build exactly the
 * same {@link PdfStructureElement} nodes that hand-written
 * `addElement` calls would produce, so the resulting tree serializes
 * (via {@link PdfStructureTree.toDict}) and validates (via
 * {@link PdfStructureTree.validate}) identically.
 *
 * Reference: ISO 32000-1 §14.7 / ISO 32000-2 §14.7 (Logical Structure),
 * Table 384 (List Attributes — the `/ListNumbering` attribute).
 */

import type {
  PdfStructureElement,
  PdfStructureTree,
  StructureElementOptions,
} from './structureTree.js';

// ---------------------------------------------------------------------------
// List numbering
// ---------------------------------------------------------------------------

/**
 * The set of values that the PDF list-attribute `/ListNumbering` may
 * take (ISO 32000, Table 384, owner `/List`).  These determine how a
 * list's item labels are presented to assistive technology:
 *
 * - `None`       — no autogenerated numbering (labels are explicit).
 * - `Disc`, `Circle`, `Square` — unordered bullet glyphs.
 * - `Decimal`    — `1`, `2`, `3`, …
 * - `UpperRoman` — `I`, `II`, `III`, …
 * - `LowerRoman` — `i`, `ii`, `iii`, …
 * - `UpperAlpha` — `A`, `B`, `C`, …
 * - `LowerAlpha` — `a`, `b`, `c`, …
 */
export type ListNumbering =
  | 'None'
  | 'Disc'
  | 'Circle'
  | 'Square'
  | 'Decimal'
  | 'UpperRoman'
  | 'LowerRoman'
  | 'UpperAlpha'
  | 'LowerAlpha';

/**
 * The property key under which {@link tagList} records the chosen
 * {@link ListNumbering} on a list element's `options` object.
 *
 * `StructureElementOptions` has no dedicated `listNumbering` field, so
 * the value is stored as an extra (string-keyed) property on the same
 * options object.  When the structure tree is serialized this is the
 * value an attribute writer should emit as the list's `/ListNumbering`
 * entry inside an `/A` attribute dictionary whose owner is `/List`
 * (ISO 32000, Table 384):
 *
 * ```
 * /A << /O /List /ListNumbering /Decimal >>
 * ```
 *
 * Using a well-known string key (rather than a `Symbol`) keeps the
 * value plain-serializable and inspectable from tests.
 */
export const LIST_NUMBERING_KEY = '__listNumbering' as const;

// ---------------------------------------------------------------------------
// Block-level helpers
// ---------------------------------------------------------------------------

/**
 * Heading level → structure-type mapping for {@link tagHeading}.
 *
 * Indexed by the numeric heading level (`1`..`6`); the result is the
 * corresponding standard heading structure type (`'H1'`..`'H6'`).
 */
const HEADING_TYPE: Readonly<Record<1 | 2 | 3 | 4 | 5 | 6, string>> = {
  1: 'H1',
  2: 'H2',
  3: 'H3',
  4: 'H4',
  5: 'H5',
  6: 'H6',
};

/**
 * Tag a heading element of the given level.
 *
 * @param tree    The structure tree to add the element to.
 * @param parent  The parent element, or `null` to add under the root
 *                `Document` element.
 * @param level   The heading level (`1`..`6`); maps to `H1`..`H6`.
 * @param options Optional attributes (title, language, id, …).
 * @returns       The newly created heading element (type `H1`..`H6`).
 *
 * @example
 * ```ts
 * const tree = doc.createStructureTree();
 * const h2 = tagHeading(tree, null, 2, { title: 'Background' });
 * // h2.type === 'H2'
 * ```
 */
export function tagHeading(
  tree: PdfStructureTree,
  parent: PdfStructureElement | null,
  level: 1 | 2 | 3 | 4 | 5 | 6,
  options?: StructureElementOptions,
): PdfStructureElement {
  return tree.addElement(parent, HEADING_TYPE[level], options);
}

/**
 * Tag a paragraph (`P`) element.
 *
 * @param tree    The structure tree to add the element to.
 * @param parent  The parent element, or `null` for the root.
 * @param options Optional attributes.
 * @returns       The newly created `P` element.
 */
export function tagParagraph(
  tree: PdfStructureTree,
  parent: PdfStructureElement | null,
  options?: StructureElementOptions,
): PdfStructureElement {
  return tree.addElement(parent, 'P', options);
}

/**
 * Tag a figure (`Figure`) element with alternative text.
 *
 * The `altText` argument is required because PDF/UA mandates
 * alternative text for illustration elements.  If the caller also
 * supplies `altText` in `options`, that explicit value takes
 * precedence over the positional argument.
 *
 * @param tree    The structure tree to add the element to.
 * @param parent  The parent element, or `null` for the root.
 * @param altText Alternative text describing the figure.
 * @param options Optional additional attributes.
 * @returns       The newly created `Figure` element with `/Alt` set.
 */
export function tagFigure(
  tree: PdfStructureTree,
  parent: PdfStructureElement | null,
  altText: string,
  options?: StructureElementOptions,
): PdfStructureElement {
  const merged: StructureElementOptions = { altText, ...options };
  return tree.addElement(parent, 'Figure', merged);
}

/**
 * Tag a link (`Link`) element.
 *
 * @param tree    The structure tree to add the element to.
 * @param parent  The parent element, or `null` for the root.
 * @param options Optional attributes.
 * @returns       The newly created `Link` element.
 */
export function tagLink(
  tree: PdfStructureTree,
  parent: PdfStructureElement | null,
  options?: StructureElementOptions,
): PdfStructureElement {
  return tree.addElement(parent, 'Link', options);
}

// ---------------------------------------------------------------------------
// List helpers
// ---------------------------------------------------------------------------

/**
 * Tag a list (`L`) element and record its numbering style.
 *
 * The chosen {@link ListNumbering} is stored on the returned element's
 * `options` object under {@link LIST_NUMBERING_KEY} (since
 * `StructureElementOptions` has no dedicated field).  A serializer can
 * emit it as the list's `/ListNumbering` attribute (ISO 32000,
 * Table 384) inside an `/A` dictionary owned by `/List`.
 *
 * @param tree      The structure tree to add the element to.
 * @param parent    The parent element, or `null` for the root.
 * @param numbering The list numbering style (default `'None'`).
 * @param options   Optional additional attributes.
 * @returns         The newly created `L` element.
 */
export function tagList(
  tree: PdfStructureTree,
  parent: PdfStructureElement | null,
  numbering: ListNumbering = 'None',
  options?: StructureElementOptions,
): PdfStructureElement {
  const list = tree.addElement(parent, 'L', options);
  // Record the numbering on the (mutable) options object using a
  // well-known string key.  `options` is a plain object, so this extra
  // property is safe and inspectable.
  (list.options as Record<string, unknown>)[LIST_NUMBERING_KEY] = numbering;
  return list;
}

/**
 * The constituent elements created for a single list item by
 * {@link tagListItem}.
 */
export interface TaggedListItem {
  /** The `LI` (list item) element. */
  readonly item: PdfStructureElement;
  /** The `Lbl` (label) element — the item's bullet/number. */
  readonly label: PdfStructureElement;
  /** The `LBody` (list body) element — the item's content. */
  readonly body: PdfStructureElement;
}

/**
 * Tag a list item under a list, building the conventional
 * `LI` → (`Lbl`, `LBody`) substructure.
 *
 * @param tree    The structure tree to add the elements to.
 * @param list    The parent `L` (list) element.
 * @param options Optional attributes for the `LI` element.
 * @returns       The created `item` (`LI`), `label` (`Lbl`) and
 *                `body` (`LBody`) elements.
 *
 * @example
 * ```ts
 * const list = tagList(tree, null, 'Decimal');
 * const { item, label, body } = tagListItem(tree, list);
 * // item.type === 'LI', label.type === 'Lbl', body.type === 'LBody'
 * ```
 */
export function tagListItem(
  tree: PdfStructureTree,
  list: PdfStructureElement,
  options?: StructureElementOptions,
): TaggedListItem {
  const item = tree.addElement(list, 'LI', options);
  const label = tree.addElement(item, 'Lbl');
  const body = tree.addElement(item, 'LBody');
  return { item, label, body };
}

// ---------------------------------------------------------------------------
// Table helpers
// ---------------------------------------------------------------------------

/**
 * Tag a table (`Table`) element.
 *
 * @param tree    The structure tree to add the element to.
 * @param parent  The parent element, or `null` for the root.
 * @param options Optional attributes.
 * @returns       The newly created `Table` element.
 */
export function tagTable(
  tree: PdfStructureTree,
  parent: PdfStructureElement | null,
  options?: StructureElementOptions,
): PdfStructureElement {
  return tree.addElement(parent, 'Table', options);
}

/**
 * Tag a table row (`TR`) under a table.
 *
 * @param tree   The structure tree to add the element to.
 * @param table  The parent `Table` element.
 * @returns      The newly created `TR` element.
 */
export function tagTableRow(
  tree: PdfStructureTree,
  table: PdfStructureElement,
): PdfStructureElement {
  return tree.addElement(table, 'TR');
}

/**
 * Tag a table header cell (`TH`) under a row, recording its scope.
 *
 * The `scope` is stored in the element's options (`/Scope` attribute,
 * one of `Row`, `Column`, or `Both`) and is used by table-header
 * validation to associate header cells with the cells they describe.
 *
 * @param tree    The structure tree to add the element to.
 * @param row     The parent `TR` element.
 * @param scope   The header scope (default `'Column'`).
 * @param options Optional additional attributes (e.g. colSpan/rowSpan).
 * @returns       The newly created `TH` element with `scope` set.
 */
export function tagTableHeaderCell(
  tree: PdfStructureTree,
  row: PdfStructureElement,
  scope: 'Row' | 'Column' | 'Both' = 'Column',
  options?: StructureElementOptions,
): PdfStructureElement {
  const merged: StructureElementOptions = { ...options, scope };
  return tree.addElement(row, 'TH', merged);
}

/**
 * Tag a table data cell (`TD`) under a row.
 *
 * @param tree    The structure tree to add the element to.
 * @param row     The parent `TR` element.
 * @param options Optional attributes (e.g. colSpan/rowSpan).
 * @returns       The newly created `TD` element.
 */
export function tagTableDataCell(
  tree: PdfStructureTree,
  row: PdfStructureElement,
  options?: StructureElementOptions,
): PdfStructureElement {
  return tree.addElement(row, 'TD', options);
}
